```mermaid
graph BT

    subgraph analysis [analysis]
    BWAS{{bellwether<br>analysis<br>service}}
    BAS{{benford<br>analysis<br>service}}
    LAS{{loyalty<br>analysis<br>service}}
    PAS{{prediction<br>analysis<br>service}}
    SAS{{spoiler<br>analysis<br>service}}
    end

    subgraph domain [domain]
    TRS{{timespace<br>reducer<br>service}}
    ERS{{election<br>result<br>service}}
    EES{{election<br>event<br>service}}
    EHS{{election<br>history<br>service}}
    LDS{{locality<br>data<br>service}}
    end

    subgraph data [data]
    ERR[(election<br>result<br>repository)]
    MERR[(mock-election<br>result<br>repository)]
    end

    ERS --> ERR
    ERS --> TRS
    EES --> ERS
    EES --> LDS
    EHS --> EES
    EHS --> ERS
```