```mermaid
graph BT

    subgraph analysis [analysis]
    BellwetherAnalysisService{{bellwether<br>analysis<br>service}}
    LoyaltyAnalysisService{{loyalty<br>analysis<br>service}}
    SpoilerAnalysisService{{spoiler<br>analysis<br>service}}
    PredictionAnalysisService{{prediction<br>analysis<br>service}}
    BenfordAnalysisService{{benford<br>analysis<br>service}}
    end

    subgraph core-domain-model [core-domain-model]
    ElectionEventsService{{election<br>events<br>service}}
    TimespaceDataService{{timespace<br>data<br>service}}
    SociologyDataService{{sociology<br>data<br>service}}
    TimespaceReducerService{{timespace<br>reducer<br>service}}
    SociologyReducerService{{sociology<br>reducer<br>service}}
    ElectionHistoryService{{election<br>history<br>service}}
    ElectionRankingService{{election<br>ranking<br>service}}
    ElectionWinnerService{{election<br>winner<br>service}}
    ElectionStreakService{{election<br>streak<br>service}}
    end

    subgraph mit-model-adapter [mit-model-adapter]
    ElectionDataListener{{election<br>data<br>listener}}
    ElectionDataService{{election<br>data<br>service}}
    end

    subgraph mit-data-model [mit-data-model]
    ElectionData((election<br>model<br>data))
    MockElectionDataRepository[(mock-election<br>data<br>repository)]
    ElectionDataRepository[(election<br>data<br>repository)]
    ElectionDataEmitter{{election<br>data<br>emitter}}
    end

    ElectionDataEmitter -->|execute `emit` when data changes| ElectionDataRepository
    ElectionDataListener --> ElectionDataEmitter
    ElectionDataService --> ElectionDataListener
    ElectionEventsService -->|observes| ElectionDataService
    ElectionHistoryService -->|lambda: order election-events by time| ElectionEventsService
    ElectionHistoryService -->|receives these two to provide data ordering to the events| TimespaceDataService
    ElectionHistoryService --> SociologyDataService
    ElectionRankingService -->|lambda: order election-results by candidate votes| ElectionHistoryService
    TimespaceDataService -->|queries for lambda statement| TimespaceReducerService
    SociologyDataService -->|queries for lambda statement| SociologyReducerService
    ElectionWinnerService --> ElectionRankingService
    ElectionStreakService --> ElectionWinnerService
    BellwetherAnalysisService -->|will only need to compare self data vs national history| ElectionWinnerService
    LoyaltyAnalysisService --> ElectionRankingService
    SpoilerAnalysisService --> ElectionRankingService
```